import { query } from '../db/pg';

export const COMPREHENSIVE_OPPORTUNITIES = [
  // =========================================================================
  // 1. PAKISTAN INTERNSHIPS (30 Items — Islamabad, Lahore, Karachi, Rawalpindi, Remote PK)
  // Target roles: AI/ML, Computer Vision, Full-Stack, Cloud/DevOps, Data Science, Cybersecurity
  // =========================================================================
  {
    title: 'Systems Limited - AI & Machine Learning Summer Internship',
    organization: 'Systems Limited Pakistan',
    type: 'Internship',
    location: 'Lahore / Islamabad / Karachi',
    deadline: 'May 15, 2026',
    status: 'Published',
    applicants_count: 124,
    match_requirement: 'BS Computer Science or AI · Python · PyTorch · Semester 5+',
    featured: true,
    compensation: 'PKR 65,000 - 85,000 / month',
    apply_url: 'https://www.systemsltd.com/careers',
    description: 'Work with the Enterprise AI team at Systems Limited. You will build machine learning models, fine-tune open-source LLMs, and develop smart APIs for real enterprise clients.',
    target_role: 'AI / Machine Learning',
    is_external: true,
  },
  {
    title: 'Arbisoft - Fresh Graduate & Student Software Engineering Internship',
    organization: 'Arbisoft',
    type: 'Internship',
    location: 'Lahore (Canal Road)',
    deadline: 'Apr 30, 2026',
    status: 'Published',
    applicants_count: 140,
    match_requirement: 'Strong Data Structures & OOP · Python or JavaScript/TypeScript · Problem Solving',
    featured: true,
    compensation: 'PKR 70,000 - 90,000 / month + Free Lunch',
    apply_url: 'https://arbisoft.com/careers',
    description: 'Arbisoft’s flagship engineering internship. You will receive 1-on-1 mentorship from principal engineers, write clean production code, and work on large-scale web applications.',
    target_role: 'Full-Stack Web Development',
    is_external: true,
  },
  {
    title: 'Motive (KeepTruckin) - Computer Vision & Edge AI Internship',
    organization: 'Motive Technologies Pakistan',
    type: 'Internship',
    location: 'Islamabad (Evacuee Trust Complex)',
    deadline: 'Jun 10, 2026',
    status: 'Published',
    applicants_count: 98,
    match_requirement: 'OpenCV · Python · Deep Learning (YOLO/PyTorch) · C++ is a plus',
    featured: true,
    compensation: 'PKR 85,000 - 110,000 / month',
    apply_url: 'https://gomotive.com/company/careers',
    description: 'Help develop real-time computer vision models for driver safety cameras. You will train object detection, driver monitoring, and road hazard detection models deployed on edge devices.',
    target_role: 'Computer Vision',
    is_external: true,
  },
  {
    title: 'Afiniti - Data Science & Behavioral AI Internship',
    organization: 'Afiniti Software',
    type: 'Internship',
    location: 'Islamabad / Lahore',
    deadline: 'May 31, 2026',
    status: 'Published',
    applicants_count: 85,
    match_requirement: 'Probability & Statistics · Pandas · Scikit-Learn · SQL · CGPA >= 3.0',
    featured: true,
    compensation: 'PKR 75,000 - 95,000 / month',
    apply_url: 'https://www.afiniti.com/careers',
    description: 'Join Afiniti’s patented Artificial Intelligence team. You will analyze large customer interaction datasets, design predictive behavioral models, and run real-world A/B experiments.',
    target_role: 'Data Science & Analytics',
    is_external: true,
  },
  {
    title: '10Pearls - Cloud & DevOps Engineering Internship',
    organization: '10Pearls Pakistan',
    type: 'Internship',
    location: 'Karachi / Islamabad / Lahore',
    deadline: 'May 20, 2026',
    status: 'Published',
    applicants_count: 92,
    match_requirement: 'Linux basics · Docker · Git · Basic knowledge of AWS or Azure',
    featured: false,
    compensation: 'PKR 55,000 - 75,000 / month',
    apply_url: 'https://10pearls.com/careers',
    description: 'Learn modern DevOps practices hands-on. You will set up CI/CD automation pipelines, containerize backend microservices with Docker, and manage cloud deployments on AWS.',
    target_role: 'Cloud & DevOps',
    is_external: true,
  },
  {
    title: 'Devsinc - Full-Stack MERN & Next.js Developer Internship',
    organization: 'Devsinc',
    type: 'Internship',
    location: 'Lahore (Johar Town) / Islamabad',
    deadline: 'May 25, 2026',
    status: 'Published',
    applicants_count: 110,
    match_requirement: 'React.js · Node.js · Express · MongoDB or PostgreSQL · JavaScript',
    featured: false,
    compensation: 'PKR 50,000 - 75,000 / month',
    apply_url: 'https://devsinc.com/careers',
    description: 'Build fast, responsive web applications using Next.js and Node.js. You will work on real client projects alongside senior web developers and learn full-stack software delivery.',
    target_role: 'Full-Stack Web Development',
    is_external: true,
  },
  {
    title: 'Jazz (VEON) - Summer Digital Ambassadorship & Data Internship',
    organization: 'Jazz (VEON Group)',
    type: 'Internship',
    location: 'Islamabad (F-8 HQ)',
    deadline: 'Jun 05, 2026',
    status: 'Published',
    applicants_count: 135,
    match_requirement: 'Python · SQL · Data Visualization (Power BI / Tableau) · Final Year or Recent Grad',
    featured: true,
    compensation: 'PKR 60,000 / month + Free Data & Calls',
    apply_url: 'https://jobs.jazz.com.pk',
    description: 'Work inside Pakistan’s largest telecom operator. You will build analytics dashboards, query big data clusters, and extract business insights for JazzCash and digital services.',
    target_role: 'Data Science & Analytics',
    is_external: true,
  },
  {
    title: 'Telenor Pakistan - Summer Associate Internship Program',
    organization: 'Telenor Pakistan',
    type: 'Internship',
    location: 'Islamabad (345 Campus, Chak Shahzad)',
    deadline: 'May 10, 2026',
    status: 'Published',
    applicants_count: 115,
    match_requirement: 'Computer Science or Software Engineering · Cloud Fundamentals · Good Communication',
    featured: false,
    compensation: 'PKR 55,000 / month + Transport Facility',
    apply_url: 'https://www.telenor.com.pk/careers',
    description: 'Experience corporate technology culture at Telenor 345 campus. You will work on digital cloud products, API integrations, and telecom customer software platforms.',
    target_role: 'Cloud & DevOps',
    is_external: true,
  },
  {
    title: 'SadaPay - Fintech Backend & Mobile Engineering Internship',
    organization: 'SadaPay',
    type: 'Internship',
    location: 'Islamabad / Remote Friendly Pakistan',
    deadline: 'May 28, 2026',
    status: 'Published',
    applicants_count: 145,
    match_requirement: 'Golang, Java, or Node.js · REST APIs · Database design · Git',
    featured: true,
    compensation: 'PKR 75,000 - 100,000 / month',
    apply_url: 'https://sadapay.pk/careers',
    description: 'Help build high-speed financial infrastructure for millions of Pakistani users. You will write clean, well-tested backend microservices and work on payment processing flows.',
    target_role: 'Full-Stack Web Development',
    is_external: true,
  },
  {
    title: 'NayaPay - Cyber Security & Penetration Testing Internship',
    organization: 'NayaPay (Pvt) Ltd',
    type: 'Internship',
    location: 'Karachi (Clifton)',
    deadline: 'Jun 15, 2026',
    status: 'Published',
    applicants_count: 70,
    match_requirement: 'Web Security fundamentals (OWASP Top 10) · Network Protocols · Linux · BurpSuite',
    featured: false,
    compensation: 'PKR 50,000 - 70,000 / month',
    apply_url: 'https://www.nayapay.com/careers',
    description: 'Assist the Information Security team at NayaPay. You will participate in vulnerability scanning, mobile application penetration testing, and help maintain PCI-DSS compliance.',
    target_role: 'Cybersecurity',
    is_external: true,
  },
  {
    title: 'VentureDive - Associate AI Solutions Engineer Internship',
    organization: 'VentureDive',
    type: 'Internship',
    location: 'Lahore / Karachi',
    deadline: 'May 18, 2026',
    status: 'Published',
    applicants_count: 88,
    match_requirement: 'Python · Scikit-Learn · NLP or Computer Vision basics · Strong Problem Solving',
    featured: false,
    compensation: 'PKR 60,000 - 80,000 / month',
    apply_url: 'https://www.venturedive.com/careers',
    description: 'Work with VentureDive’s AI studio to build intelligent products for international clients. You will build computer vision pipelines, text classification models, and conversational agents.',
    target_role: 'AI / Machine Learning',
    is_external: true,
  },
  {
    title: 'Educative, Inc. - Software Engineering & Tech Curriculum Internship',
    organization: 'Educative, Inc. Pakistan',
    type: 'Internship',
    location: 'Lahore (Gulberg)',
    deadline: 'Jun 01, 2026',
    status: 'Published',
    applicants_count: 95,
    match_requirement: 'Data Structures & Algorithms · Python or Java · Technical writing & coding skills',
    featured: false,
    compensation: 'PKR 65,000 - 85,000 / month',
    apply_url: 'https://www.educative.io/careers',
    description: 'Educative serves millions of developers worldwide. In this role, you will build hands-on coding environments, write technical lessons, and test interactive developer tools.',
    target_role: 'Full-Stack Web Development',
    is_external: true,
  },
  {
    title: 'NetSol Technologies - Enterprise Cloud Solutions Internship',
    organization: 'NetSol Technologies Ltd',
    type: 'Internship',
    location: 'Lahore (NetSol IT Village, Ring Road)',
    deadline: 'May 30, 2026',
    status: 'Published',
    applicants_count: 78,
    match_requirement: 'C# / .NET Core or Java · SQL Server · Object Oriented Programming',
    featured: false,
    compensation: 'PKR 50,000 - 70,000 / month',
    apply_url: 'https://netsoltech.com/careers',
    description: 'NetSol is a pioneer in Pakistani IT. You will work on their global asset finance and leasing cloud software, writing enterprise APIs and learning scalable software architecture.',
    target_role: 'Cloud & DevOps',
    is_external: true,
  },
  {
    title: 'Contour Software (Constellation Software) - Junior Systems & C++ Internship',
    organization: 'Contour Software Pakistan',
    type: 'Internship',
    location: 'Karachi / Lahore / Islamabad',
    deadline: 'Jun 12, 2026',
    status: 'Published',
    applicants_count: 65,
    match_requirement: 'C++ or C# · Memory management · Operating Systems fundamentals · Clean code',
    featured: false,
    compensation: 'PKR 65,000 - 85,000 / month',
    apply_url: 'https://contour-software.com/careers',
    description: 'Contour Software develops mission-critical software for Constellation Software Inc. You will debug complex enterprise systems, optimize performance, and write robust code.',
    target_role: 'Full-Stack Web Development',
    is_external: true,
  },
  {
    title: 'Emumba - High-Performance Networking & Cloud Intern',
    organization: 'Emumba',
    type: 'Internship',
    location: 'Islamabad (I-9)',
    deadline: 'May 22, 2026',
    status: 'Published',
    applicants_count: 72,
    match_requirement: 'Computer Networks · Linux Kernels · C/C++ or Go · Good communication',
    featured: false,
    compensation: 'PKR 60,000 - 80,000 / month',
    apply_url: 'https://emumba.com/careers',
    description: 'Emumba works on cutting-edge computer networking and cloud acceleration. You will work with DPDK, high-throughput network packets, and modern cloud infrastructure.',
    target_role: 'Cloud & DevOps',
    is_external: true,
  },
  {
    title: 'i2c Inc. - Payments Architecture & Cyber Security Internship',
    organization: 'i2c Inc. Pakistan',
    type: 'Internship',
    location: 'Lahore (Canal Bank)',
    deadline: 'Jun 20, 2026',
    status: 'Published',
    applicants_count: 82,
    match_requirement: 'Network Security · Cryptography basics · Java / Linux · Analytical thinking',
    featured: false,
    compensation: 'PKR 55,000 - 75,000 / month',
    apply_url: 'https://www.i2cinc.com/careers',
    description: 'i2c powers billions of global card payments. In this internship, you will learn secure transaction processing, tokenization, fraud detection, and enterprise cyber defense.',
    target_role: 'Cybersecurity',
    is_external: true,
  },
  {
    title: 'Folio3 - Computer Vision & Deep Learning AgriTech Internship',
    organization: 'Folio3 Software',
    type: 'Internship',
    location: 'Karachi / Lahore / Islamabad',
    deadline: 'May 16, 2026',
    status: 'Published',
    applicants_count: 64,
    match_requirement: 'Computer Vision · OpenCV · PyTorch · Image Processing · Python',
    featured: true,
    compensation: 'PKR 60,000 - 85,000 / month',
    apply_url: 'https://folio3.com/careers',
    description: 'Build smart computer vision systems for Folio3’s animal and plant health AI division. You will work on livestock tracking, crop disease detection, and thermal image analysis.',
    target_role: 'Computer Vision',
    is_external: true,
  },
  {
    title: 'Confiz - Modern Frontend React & Next.js Internship',
    organization: 'Confiz',
    type: 'Internship',
    location: 'Lahore (Gulberg III)',
    deadline: 'May 25, 2026',
    status: 'Published',
    applicants_count: 90,
    match_requirement: 'HTML5 · CSS3 / Tailwind · Modern JavaScript / TypeScript · React basics',
    featured: false,
    compensation: 'PKR 50,000 - 70,000 / month',
    apply_url: 'https://www.confiz.com/careers',
    description: 'Create user interfaces for global retail and supply chain web platforms. You will write reusable React components, connect REST APIs, and optimize web performance.',
    target_role: 'Full-Stack Web Development',
    is_external: true,
  },
  {
    title: 'Tkxel - Data Engineering & Business Intelligence Internship',
    organization: 'Tkxel',
    type: 'Internship',
    location: 'Lahore (Johar Town)',
    deadline: 'Jun 05, 2026',
    status: 'Published',
    applicants_count: 75,
    match_requirement: 'SQL · Python · ETL Pipelines · Power BI or Tableau · Excel',
    featured: false,
    compensation: 'PKR 50,000 - 70,000 / month',
    apply_url: 'https://tkxel.com/careers',
    description: 'Learn data pipeline design from scratch. You will extract and clean data from diverse sources, build automated SQL reporting workflows, and deliver visual business dashboards.',
    target_role: 'Data Science & Analytics',
    is_external: true,
  },
  {
    title: 'Tintash - Python Machine Learning & Game Tech Internship',
    organization: 'Tintash',
    type: 'Internship',
    location: 'Lahore (DHA Phase 5)',
    deadline: 'May 31, 2026',
    status: 'Published',
    applicants_count: 68,
    match_requirement: 'Python · Linear Algebra · Basic ML concepts · Strong problem solving',
    featured: false,
    compensation: 'PKR 55,000 - 75,000 / month',
    apply_url: 'https://tintash.com/careers',
    description: 'Tintash creates award-winning digital games and apps. You will collaborate with product teams to build gameplay AI, recommendation algorithms, and backend game services.',
    target_role: 'AI / Machine Learning',
    is_external: true,
  },
  {
    title: 'Nayatel - Telecom IP Networks & Linux Systems Internship',
    organization: 'Nayatel (Pvt) Ltd',
    type: 'Internship',
    location: 'Islamabad / Rawalpindi',
    deadline: 'May 12, 2026',
    status: 'Published',
    applicants_count: 80,
    match_requirement: 'CCNA basics · Linux command line · Routing & Switching · Shell Scripting',
    featured: false,
    compensation: 'PKR 45,000 - 60,000 / month',
    apply_url: 'https://nayatel.com/careers',
    description: 'Gain practical networking experience on Nayatel’s fiber-optic infrastructure. You will assist network operations engineers with routing tables, BGP peering, and server monitoring.',
    target_role: 'Cloud & DevOps',
    is_external: true,
  },
  {
    title: 'Zigron - IoT & Embedded Computer Vision Internship',
    organization: 'Zigron Inc.',
    type: 'Internship',
    location: 'Islamabad (I-8)',
    deadline: 'Jun 18, 2026',
    status: 'Published',
    applicants_count: 58,
    match_requirement: 'Raspberry Pi / Jetson · C++ or Python · OpenCV · Sensor interfacing',
    featured: false,
    compensation: 'PKR 60,000 - 80,000 / month',
    apply_url: 'https://zigron.com/careers',
    description: 'Work on smart IoT hardware and edge computer vision. You will deploy lightweight neural networks on edge compute boards for automated license plate and facial detection.',
    target_role: 'Computer Vision',
    is_external: true,
  },
  {
    title: 'Bykea - Backend Microservices & Logistics Tech Internship',
    organization: 'Bykea Technologies',
    type: 'Internship',
    location: 'Karachi / Lahore',
    deadline: 'Jun 10, 2026',
    status: 'Published',
    applicants_count: 85,
    match_requirement: 'Node.js or Go · PostgreSQL · Redis · Distributed Systems basics',
    featured: false,
    compensation: 'PKR 60,000 - 80,000 / month',
    apply_url: 'https://bykea.com/careers',
    description: 'Work on high-frequency dispatch engines and location tracking. You will optimize geo-hashing queries, handle concurrent order spikes, and build real-time driver matching logic.',
    target_role: 'Full-Stack Web Development',
    is_external: true,
  },
  {
    title: 'Bazaar Technologies - Retail Tech & Data Science Internship',
    organization: 'Bazaar Technologies',
    type: 'Internship',
    location: 'Karachi (HQ) / Lahore',
    deadline: 'May 20, 2026',
    status: 'Published',
    applicants_count: 76,
    match_requirement: 'Python · Pandas · Forecasting models · SQL · Business acumen',
    featured: true,
    compensation: 'PKR 65,000 - 85,000 / month',
    apply_url: 'https://bazaartech.com/careers',
    description: 'Help optimize B2B supply chains for retail shopkeepers across Pakistan. You will build product demand forecasting models and dynamic inventory restocking algorithms.',
    target_role: 'Data Science & Analytics',
    is_external: true,
  },
  {
    title: 'Strategic Systems International (SSI) - AI/NLP Research Internship',
    organization: 'SSI (Strategic Systems International)',
    type: 'Internship',
    location: 'Lahore (Canal Road)',
    deadline: 'May 24, 2026',
    status: 'Published',
    applicants_count: 62,
    match_requirement: 'Natural Language Processing · HuggingFace Transformers · Python · PyTorch',
    featured: false,
    compensation: 'PKR 60,000 - 80,000 / month',
    apply_url: 'https://ssidecisions.com/careers',
    description: 'Join SSI’s advanced analytics team. You will experiment with retrieval-augmented generation (RAG), vector databases, and fine-tuning language models for international clients.',
    target_role: 'AI / Machine Learning',
    is_external: true,
  },
  {
    title: 'Techlogix - Financial Cloud Applications Internship',
    organization: 'Techlogix Pakistan',
    type: 'Internship',
    location: 'Lahore / Islamabad / Karachi',
    deadline: 'Jun 08, 2026',
    status: 'Published',
    applicants_count: 70,
    match_requirement: 'Java or C# · Object-oriented design · Relational Databases · Semester 6+',
    featured: false,
    compensation: 'PKR 55,000 - 70,000 / month',
    apply_url: 'https://www.techlogix.com/careers',
    description: 'Work on enterprise digital banking platforms and middleware. You will learn modern software engineering practices, automated testing, and secure financial integrations.',
    target_role: 'Cloud & DevOps',
    is_external: true,
  },
  {
    title: 'Careem Pakistan - Software Engineering Core Ride & Food Tech Intern',
    organization: 'Careem (An Uber Company)',
    type: 'Internship',
    location: 'Karachi / Lahore / Islamabad',
    deadline: 'May 27, 2026',
    status: 'Published',
    applicants_count: 120,
    match_requirement: 'Algorithms & Data Structures · Java / Spring Boot or Python · Clean code',
    featured: true,
    compensation: 'PKR 80,000 - 105,000 / month',
    apply_url: 'https://careers.careem.com',
    description: 'Build backend features for the Careem Super App. You will work on real-time ride tracking, dispatch algorithms, coupon engines, and low-latency microservices.',
    target_role: 'Full-Stack Web Development',
    is_external: true,
  },
  {
    title: 'Dukan.pk - Mobile App & Flutter Development Internship',
    organization: 'Dukan.pk',
    type: 'Internship',
    location: 'Lahore (Gulberg)',
    deadline: 'Jun 14, 2026',
    status: 'Published',
    applicants_count: 60,
    match_requirement: 'Flutter / Dart · State Management (Bloc / Provider) · REST API integration',
    featured: false,
    compensation: 'PKR 50,000 - 70,000 / month',
    apply_url: 'https://dukan.pk/careers',
    description: 'Build user-friendly mobile features for Pakistani small merchants. You will design fast mobile checkout screens, offline product catalogs, and WhatsApp shop integrations.',
    target_role: 'Full-Stack Web Development',
    is_external: true,
  },
  {
    title: 'Trillium Information Security - Defensive Cyber & SOC Analyst Internship',
    organization: 'Trillium Security Systems',
    type: 'Internship',
    location: 'Islamabad / Rawalpindi',
    deadline: 'May 29, 2026',
    status: 'Published',
    applicants_count: 55,
    match_requirement: 'SIEM basics (Splunk / Elastic) · Network Traffic Analysis (Wireshark) · Linux',
    featured: false,
    compensation: 'PKR 50,000 - 70,000 / month',
    apply_url: 'https://trilliumnet.com/careers',
    description: 'Train inside a live Security Operations Center (SOC). You will inspect firewall logs, analyze suspicious malware payloads, and help mitigate cyber security incidents.',
    target_role: 'Cybersecurity',
    is_external: true,
  },
  {
    title: 'Remotebase Pakistan - Remote Global Software Engineering Fellow',
    organization: 'Remotebase',
    type: 'Internship',
    location: 'Remote Pakistan (Islamabad / Lahore / Karachi)',
    deadline: 'Jun 25, 2026',
    status: 'Published',
    applicants_count: 150,
    match_requirement: 'Full-Stack (React & Node.js or Python) · Git · Good English communication',
    featured: true,
    compensation: 'PKR 65,000 - 90,000 / month',
    apply_url: 'https://remotebase.com/careers',
    description: 'Work remotely from anywhere in Pakistan on US Silicon Valley startup projects. You will sharpen your full-stack development skills, write unit tests, and ship production features.',
    target_role: 'Full-Stack Web Development',
    is_external: true,
  },

  // =========================================================================
  // 2. PAKISTAN HACKATHONS & COMPETITIONS (30 Items — Islamabad, Lahore, Karachi & National)
  // =========================================================================
  {
    title: 'FAST-NUCES NASCON - National Speed Programming & AI Challenge',
    organization: 'FAST-NUCES Islamabad Campus',
    type: 'Competition',
    location: 'Islamabad (FAST-NUCES Campus, H-11/4)',
    deadline: 'Apr 20, 2026',
    status: 'Published',
    applicants_count: 310,
    match_requirement: 'Teams of 2-3 · University students · C++, Java, or Python',
    featured: true,
    compensation: 'PKR 250,000 Cash Prize + National Trophy',
    apply_url: 'https://nascon.org.pk',
    description: 'Pakistan’s premier student computing Olympiad. Teams compete in high-speed algorithmic problem solving, machine learning model building, and dynamic data challenges.',
    target_role: 'AI / Machine Learning',
    is_external: true,
  },
  {
    title: 'FAST-NUCES SOFTEC - All-Pakistan Software Exhibition & Hackathon',
    organization: 'FAST-NUCES Lahore Campus',
    type: 'Hackathon',
    location: 'Lahore (FAST-NUCES Campus, Faisal Town)',
    deadline: 'May 05, 2026',
    status: 'Published',
    applicants_count: 340,
    match_requirement: 'Undergraduate students · Software projects / prototypes · Teams of 2-4',
    featured: true,
    compensation: 'PKR 300,000 Cash Prize + Industry Sponsorships',
    apply_url: 'https://softecnu.org',
    description: 'One of the oldest and largest student tech competitions in Pakistan. Showcase your working web, mobile, or AI software projects to top software house CEOs and win cash prizes.',
    target_role: 'Full-Stack Web Development',
    is_external: true,
  },
  {
    title: 'NUST COMPPEC - National Computer Project & AI Exhibition',
    organization: 'NUST College of E&ME',
    type: 'Competition',
    location: 'Rawalpindi / Islamabad (Peshawar Road)',
    deadline: 'May 12, 2026',
    status: 'Published',
    applicants_count: 220,
    match_requirement: 'Engineering & Computing students · AI, Embedded Systems, or Computer Vision projects',
    featured: true,
    compensation: 'PKR 200,000 Cash Prizes + Shields',
    apply_url: 'https://ceme.nust.edu.pk',
    description: 'Prestigious national exhibition for final-year and undergraduate computing projects. Focus areas include computer vision, autonomous robotics, AI, and smart hardware.',
    target_role: 'Computer Vision',
    is_external: true,
  },
  {
    title: 'Ignite National Cyber Security Hackathon',
    organization: 'Ministry of IT & Telecom / Ignite Pakistan',
    type: 'Hackathon',
    location: 'Islamabad / Lahore / Karachi (Regional & Finals)',
    deadline: 'Jun 15, 2026',
    status: 'Published',
    applicants_count: 480,
    match_requirement: 'Pakistani university students & young professionals · Capture the Flag (CTF)',
    featured: true,
    compensation: 'PKR 1,000,000 Grand Prize Pool',
    apply_url: 'https://ignite.net.pk',
    description: 'Pakistan’s largest government-backed cyber defense challenge. Compete in Jeopardy-style CTF challenges including web exploitation, binary reverse engineering, and forensics.',
    target_role: 'Cybersecurity',
    is_external: true,
  },
  {
    title: 'Ignite National Grassroots ICT Research & Innovation (NGIRI)',
    organization: 'Ignite National Technology Fund',
    type: 'Competition',
    location: 'Islamabad / Nationwide (All Universities)',
    deadline: 'Apr 30, 2026',
    status: 'Published',
    applicants_count: 650,
    match_requirement: 'Final Year Project (FYP) students in CS, SE, EE from HEC-recognized universities',
    featured: true,
    compensation: 'Up to PKR 85,000 Project Funding + National Awards',
    apply_url: 'https://ignite.net.pk/ngiri',
    description: 'Federal government grant initiative that funds promising final-year computing projects. Outstanding projects compete at the National Championship for cash prizes.',
    target_role: 'AI / Machine Learning',
    is_external: true,
  },
  {
    title: 'LUMS CodeFest - Competitive Programming & Algorithm Showdown',
    organization: 'LUMS Society of Professional Engineers (SPEN)',
    type: 'Competition',
    location: 'Lahore (LUMS Campus, DHA Phase 5)',
    deadline: 'May 08, 2026',
    status: 'Published',
    applicants_count: 190,
    match_requirement: 'Competitive coders · C++, Java, or Python · Solo or pairs',
    featured: false,
    compensation: 'PKR 150,000 Cash Prize + LUMS Certification',
    apply_url: 'https://lums.edu.pk',
    description: 'Tough, exciting algorithmic challenge hosted on Codeforces/HackerRank style platforms. Test your speed in dynamic programming, graph traversal, and mathematical algorithms.',
    target_role: 'Full-Stack Web Development',
    is_external: true,
  },
  {
    title: 'LUMS PSIFI - Pakistan Science & Innovation Fair Hackathon',
    organization: 'Lahore University of Management Sciences (LUMS)',
    type: 'Hackathon',
    location: 'Lahore (LUMS Campus)',
    deadline: 'May 14, 2026',
    status: 'Published',
    applicants_count: 210,
    match_requirement: 'College & University students · Teams of 3-5 · Working software prototypes',
    featured: false,
    compensation: 'PKR 200,000 Cash Awards + Incubation Support',
    apply_url: 'https://psifi.lums.edu.pk',
    description: '3-day innovation festival where students build tech solutions for local community challenges. Categories include healthcare AI, clean energy tech, and smart education.',
    target_role: 'AI / Machine Learning',
    is_external: true,
  },
  {
    title: 'FAST-NUCES Procom - National Tech Championship & App Challenge',
    organization: 'FAST-NUCES Karachi Campus',
    type: 'Competition',
    location: 'Karachi (FAST-NUCES Campus, Shah Latif Town)',
    deadline: 'May 18, 2026',
    status: 'Published',
    applicants_count: 275,
    match_requirement: 'Undergraduate teams · Web, Mobile, or AI app submissions',
    featured: false,
    compensation: 'PKR 250,000 Cash Prizes + Trophies',
    apply_url: 'https://khi.nu.edu.pk',
    description: 'South Pakistan’s premier university tech event. Competitions include speed programming, mobile app development, UI/UX design battles, and cybersecurity CTF.',
    target_role: 'Full-Stack Web Development',
    is_external: true,
  },
  {
    title: 'GIKI IEEE Softcom - All Pakistan Software & Game Dev Competition',
    organization: 'Ghulam Ishaq Khan Institute (GIKI)',
    type: 'Competition',
    location: 'Topi / Swabi (GIKI Campus)',
    deadline: 'May 22, 2026',
    status: 'Published',
    applicants_count: 180,
    match_requirement: 'University students · Game development / Software applications',
    featured: false,
    compensation: 'PKR 200,000 Cash Prizes + GIKI Awards',
    apply_url: 'https://giki.edu.pk',
    description: 'Annual technical festival at GIKI. Showcase innovative indie games, AI prototypes, and cloud systems while networking with industry recruiters and fellow students.',
    target_role: 'Full-Stack Web Development',
    is_external: true,
  },
  {
    title: 'ACM ICPC Pakistan Regional Programming Contest',
    organization: 'International Collegiate Programming Contest (ICPC)',
    type: 'Competition',
    location: 'Islamabad / Lahore (Host Universities)',
    deadline: 'Oct 15, 2026',
    status: 'Published',
    applicants_count: 290,
    match_requirement: 'Teams of 3 students from same university · Official ICPC rules · C++/Java/Python',
    featured: true,
    compensation: 'Regional Gold Medals + Qualification to ICPC World Finals',
    apply_url: 'https://icpc.global',
    description: 'The Olympics of competitive programming. Solve 10-12 hard algorithmic problems within 5 hours sharing a single computer. Winners represent Pakistan at the ICPC World Finals.',
    target_role: 'Full-Stack Web Development',
    is_external: true,
  },
  {
    title: 'IEEE Xtreme Pakistan Section - 24-Hour Virtual Programming Contest',
    organization: 'IEEE Pakistan Section / IEEE Global',
    type: 'Competition',
    location: 'Virtual / All Pakistan University Labs',
    deadline: 'Oct 05, 2026',
    status: 'Published',
    applicants_count: 420,
    match_requirement: 'IEEE Student Members · Teams of up to 3 · 24-hour endurance coding',
    featured: false,
    compensation: 'National Rankings + IEEE Digital Badges & Swag',
    apply_url: 'https://ieeextreme.org',
    description: 'A non-stop 24-hour global coding marathon. Compete from your university lab against thousands of student teams worldwide in data structures, graph theory, and math problems.',
    target_role: 'Full-Stack Web Development',
    is_external: true,
  },
  {
    title: 'Microsoft Imagine Cup Pakistan National Finals',
    organization: 'Microsoft Pakistan & HEC',
    type: 'Competition',
    location: 'Islamabad (Microsoft Innovation Center)',
    deadline: 'Jan 20, 2027',
    status: 'Published',
    applicants_count: 360,
    match_requirement: 'Students 16+ · Use Microsoft Azure or AI services · Working prototype',
    featured: true,
    compensation: '$10,000 USD Seed Grant + Trip to Global World Finals',
    apply_url: 'https://imaginecup.microsoft.com',
    description: 'Build tech for good using Azure AI. The top Pakistani student team wins a trip to the Global World Championship and gets direct mentoring from Microsoft executives.',
    target_role: 'AI / Machine Learning',
    is_external: true,
  },
  {
    title: 'Google Developer Student Clubs (GDSC) Pakistan Solution Challenge',
    organization: 'Google for Developers Pakistan',
    type: 'Hackathon',
    location: 'Islamabad / Lahore / Karachi (Virtual + Local Chapters)',
    deadline: 'Mar 15, 2027',
    status: 'Published',
    applicants_count: 510,
    match_requirement: 'Enrolled students · Solve one of the 17 UN Sustainable Development Goals',
    featured: true,
    compensation: '$3,000 Mentorship Grant + Google Swag + Global Demo Day',
    apply_url: 'https://developers.google.com/community/gdsc-solution-challenge',
    description: 'Build software using Google technologies (Flutter, Firebase, TensorFlow, Google Cloud) that solves a real social or economic problem in your local Pakistani community.',
    target_role: 'Full-Stack Web Development',
    is_external: true,
  },
  {
    title: 'NASA Space Apps Challenge Islamabad',
    organization: 'NASA / Local Islamabad Chapter',
    type: 'Hackathon',
    location: 'Islamabad (In-person & Virtual)',
    deadline: 'Sep 25, 2026',
    status: 'Published',
    applicants_count: 290,
    match_requirement: 'Open to all students, developers, and designers · 48-hour hackathon',
    featured: false,
    compensation: 'Official NASA Global Nominee Certificate + Local Awards',
    apply_url: 'https://www.spaceappschallenge.org',
    description: 'The world’s largest global space hackathon. Use open NASA Earth and space datasets to solve real-world problems regarding satellite data, climate, and space exploration.',
    target_role: 'Data Science & Analytics',
    is_external: true,
  },
  {
    title: 'NASA Space Apps Challenge Lahore',
    organization: 'NASA / Local Lahore Chapter',
    type: 'Hackathon',
    location: 'Lahore (In-person & Virtual)',
    deadline: 'Sep 25, 2026',
    status: 'Published',
    applicants_count: 310,
    match_requirement: 'Open to all Pakistani students · 48-hour sprint · Open NASA data',
    featured: false,
    compensation: 'Official NASA Global Nominee Certificate + Cash Prizes',
    apply_url: 'https://www.spaceappschallenge.org',
    description: 'Join hundreds of young coders in Lahore for a weekend sprint. Build interactive web visualizations, machine learning classifiers, or 3D models using NASA satellite imagery.',
    target_role: 'Data Science & Analytics',
    is_external: true,
  },
  {
    title: 'NASA Space Apps Challenge Karachi',
    organization: 'NASA / Local Karachi Chapter',
    type: 'Hackathon',
    location: 'Karachi (In-person & Virtual)',
    deadline: 'Sep 25, 2026',
    status: 'Published',
    applicants_count: 280,
    match_requirement: 'Open to all Pakistani students · Teams of 2-6 coders and designers',
    featured: false,
    compensation: 'Official NASA Global Nominee Certificate + Trophies',
    apply_url: 'https://www.spaceappschallenge.org',
    description: 'Karachi edition of NASA Space Apps. Collaborate with peers to build data-driven apps addressing ocean conservation, planetary mapping, or space biology challenges.',
    target_role: 'Data Science & Analytics',
    is_external: true,
  },
  {
    title: 'HEC All-Pakistan Inter-University Programming Challenge',
    organization: 'Higher Education Commission (HEC) Pakistan',
    type: 'Competition',
    location: 'Islamabad (HEC Auditorium, H-9)',
    deadline: 'May 30, 2026',
    status: 'Published',
    applicants_count: 240,
    match_requirement: 'Nominations through University CS Departments · Teams of 3',
    featured: false,
    compensation: 'PKR 500,000 National Prize Pool',
    apply_url: 'https://hec.gov.pk',
    description: 'Official national collegiate coding contest organized by HEC. Top university computing departments send their best algorithmic problem solvers to compete for national glory.',
    target_role: 'Full-Stack Web Development',
    is_external: true,
  },
  {
    title: 'Jazz Digital Pakistan Hackathon',
    organization: 'Jazz Telecom & National Incubation Center (NIC)',
    type: 'Hackathon',
    location: 'Islamabad (NIC Islamabad, H-9)',
    deadline: 'Jun 20, 2026',
    status: 'Published',
    applicants_count: 260,
    match_requirement: 'Developers & Innovators · Solutions in FinTech, HealthTech, or AgriTech',
    featured: true,
    compensation: 'PKR 1,000,000 Seed Grant + Incubation',
    apply_url: 'https://jazz.com.pk',
    description: 'Create digital products that can leverage Jazz’s customer network and open APIs. Winning teams receive cash grants and potential investment from Jazz digital ecosystem.',
    target_role: 'Cloud & DevOps',
    is_external: true,
  },
  {
    title: 'Telenor Velocity Accelerator Startup & Tech Challenge',
    organization: 'Telenor Pakistan Velocity',
    type: 'Hackathon',
    location: 'Islamabad (Telenor 345 Campus)',
    deadline: 'Jun 25, 2026',
    status: 'Published',
    applicants_count: 195,
    match_requirement: 'Student & Early-stage tech startups · Scalable digital prototype',
    featured: false,
    compensation: 'PKR 1,500,000 Pilot Funding & Cloud Credits',
    apply_url: 'https://velocity.telenor.com.pk',
    description: 'Fast-track your tech product with Telenor Velocity. Gain access to Telenor’s developer APIs, payment gateways, and receive mentorship from senior business leaders.',
    target_role: 'Cloud & DevOps',
    is_external: true,
  },
  {
    title: 'She Loves Tech Pakistan - Women in Tech Competition',
    organization: 'She Loves Tech & CIRCLE Pakistan',
    type: 'Competition',
    location: 'Karachi / Islamabad / Virtual',
    deadline: 'Jul 15, 2026',
    status: 'Published',
    applicants_count: 170,
    match_requirement: 'At least one female co-founder or tech lead · Tech prototype',
    featured: true,
    compensation: '$15,000 Equity-Free Grant + Global Finals in Singapore',
    apply_url: 'https://circlewomen.org/shelovestech',
    description: 'The world’s largest startup competition for women and technology. Pakistani female developers and innovators showcase cutting-edge apps and compete for international funding.',
    target_role: 'Full-Stack Web Development',
    is_external: true,
  },
  {
    title: 'UET Lahore I-Code Programming Olympiad',
    organization: 'University of Engineering and Technology (UET) Lahore',
    type: 'Competition',
    location: 'Lahore (UET Main Campus, GT Road)',
    deadline: 'May 10, 2026',
    status: 'Published',
    applicants_count: 200,
    match_requirement: 'Enrolled BS students · C++, Java, or Python · Algorithmic challenges',
    featured: false,
    compensation: 'PKR 100,000 Cash Prizes + Trophies',
    apply_url: 'https://uet.edu.pk',
    description: 'High-octane coding contest hosted by UET Computer Science society. Solve fast mathematical, search, and sorting algorithms under tight time constraints.',
    target_role: 'Full-Stack Web Development',
    is_external: true,
  },
  {
    title: 'NED University ITCN Asia Hackathon',
    organization: 'NED University & Ecommerce Gateway',
    type: 'Hackathon',
    location: 'Karachi (Expo Centre Karachi)',
    deadline: 'Aug 10, 2026',
    status: 'Published',
    applicants_count: 310,
    match_requirement: 'Students and fresh grads · Teams of 2-4 · Web, Mobile, or AI prototypes',
    featured: false,
    compensation: 'PKR 300,000 Cash Awards + Investor Pitches',
    apply_url: 'https://itcnasia.com',
    description: 'Held alongside Pakistan’s largest information technology trade show. Pitch your software solution directly on stage in front of major local and international venture capitalists.',
    target_role: 'Cloud & DevOps',
    is_external: true,
  },
  {
    title: 'Pak-Austria FH Artificial Intelligence & Robotics Challenge',
    organization: 'Pak-Austria Fachhochschule Institute (PAF-IAST)',
    type: 'Competition',
    location: 'Haripur / Islamabad',
    deadline: 'May 28, 2026',
    status: 'Published',
    applicants_count: 160,
    match_requirement: 'AI / Robotics enthusiasts · Computer Vision or Embedded Robotics projects',
    featured: false,
    compensation: 'PKR 350,000 Cash Prizes',
    apply_url: 'https://paf-iast.edu.pk',
    description: 'Showcase autonomous drones, vision-guided mobile robots, and edge AI projects. Evaluated by Austrian and Pakistani engineering faculty members.',
    target_role: 'Computer Vision',
    is_external: true,
  },
  {
    title: 'PyData Islamabad Datathon & ML Challenge',
    organization: 'PyData Pakistan / NumFOCUS',
    type: 'Competition',
    location: 'Islamabad (National Library Auditorium)',
    deadline: 'Jun 05, 2026',
    status: 'Published',
    applicants_count: 180,
    match_requirement: 'Python · Scikit-Learn / PyTorch · Data wrangling & visualization',
    featured: false,
    compensation: 'PKR 100,000 Cash + Cloud Credits',
    apply_url: 'https://pydata.org',
    description: 'A 24-hour sprint analyzing real Pakistani public datasets (health, inflation, traffic). Clean messy data, build predictive machine learning models, and present your findings.',
    target_role: 'Data Science & Analytics',
    is_external: true,
  },
  {
    title: 'Fintech Hackathon Pakistan by State Bank & 1Link',
    organization: 'State Bank of Pakistan & 1Link',
    type: 'Hackathon',
    location: 'Karachi (SBP Headquarters)',
    deadline: 'Jul 10, 2026',
    status: 'Published',
    applicants_count: 220,
    match_requirement: 'Fintech developers · Open Banking APIs · Digital identity & payments',
    featured: true,
    compensation: 'PKR 1,000,000 Grand Prize Pool',
    apply_url: 'https://1link.net.pk',
    description: 'Create innovative digital payment solutions using Raast instant payment rails. Build apps that enhance financial inclusion and micro-payments for everyday Pakistanis.',
    target_role: 'Cybersecurity',
    is_external: true,
  },
  {
    title: 'CyberHack Pakistan by Air University & CAC',
    organization: 'Air University Cyber Security Department',
    type: 'Hackathon',
    location: 'Islamabad (Air University Campus, E-9)',
    deadline: 'May 15, 2026',
    status: 'Published',
    applicants_count: 230,
    match_requirement: 'CTF players · Cryptography · Reverse engineering · Web app security',
    featured: false,
    compensation: 'PKR 250,000 Cash Prizes + Cyber Badges',
    apply_url: 'https://au.edu.pk',
    description: 'Flagship Capture The Flag contest by Pakistan’s top cybersecurity university. Solve defense and offensive challenges designed by senior cyber defense researchers.',
    target_role: 'Cybersecurity',
    is_external: true,
  },
  {
    title: 'RoboQuest National Robotics & Vision Challenge',
    organization: 'NUST College of EME',
    type: 'Competition',
    location: 'Rawalpindi / Islamabad',
    deadline: 'Jun 01, 2026',
    status: 'Published',
    applicants_count: 175,
    match_requirement: 'Autonomous robots · Line following / Vision-guided robots · University teams',
    featured: false,
    compensation: 'PKR 200,000 Cash Awards + Trophies',
    apply_url: 'https://ceme.nust.edu.pk',
    description: 'Test your vision-guided and autonomous robots in obstacle navigation and maze solving. Connect with Pakistan’s top roboticists and mechanical engineers.',
    target_role: 'Computer Vision',
    is_external: true,
  },
  {
    title: 'Game Jam Pakistan - 48-Hour National Game Development',
    organization: 'IGDA Pakistan & Mindstorm Studios',
    type: 'Hackathon',
    location: 'Lahore / Karachi / Islamabad / Virtual',
    deadline: 'Jul 20, 2026',
    status: 'Published',
    applicants_count: 320,
    match_requirement: 'Game devs & 3D artists · Unity, Unreal, or Godot · 48-hour build',
    featured: false,
    compensation: 'PKR 200,000 Cash + Publishing Deals with Global Studios',
    apply_url: 'https://gamejampakistan.com',
    description: 'Make a complete video game in 48 hours based on a surprise creative theme. Pitch to veteran game publishers and get feedback on gameplay mechanics and art style.',
    target_role: 'Full-Stack Web Development',
    is_external: true,
  },
  {
    title: 'NUST EMERGE AI & Social Impact Hackathon',
    organization: 'NUST Science Society',
    type: 'Hackathon',
    location: 'Islamabad (NUST H-12 Campus)',
    deadline: 'May 16, 2026',
    status: 'Published',
    applicants_count: 240,
    match_requirement: 'Undergraduate teams · Web, Mobile, or AI prototypes for social impact',
    featured: false,
    compensation: 'PKR 150,000 Cash Prizes',
    apply_url: 'https://nust.edu.pk',
    description: 'Collaborate over 36 hours at NUST H-12 to build AI-driven solutions for public health, literacy, flood warnings, and urban safety in Pakistan.',
    target_role: 'AI / Machine Learning',
    is_external: true,
  },
  {
    title: 'CodeGirls Pakistan National Hackathon',
    organization: 'CodeGirls by ConsulNet Corporation',
    type: 'Hackathon',
    location: 'Karachi (Virtual & In-person)',
    deadline: 'Jun 28, 2026',
    status: 'Published',
    applicants_count: 190,
    match_requirement: 'Female coders from any Pakistani institute · Frontend / Full-stack projects',
    featured: false,
    compensation: 'PKR 150,000 Grants + Laptops & Tech Swag',
    apply_url: 'https://codegirls.consulnet.net',
    description: 'Empowering Pakistani women in software engineering. Build accessible web portals, mobile tools, and ecommerce platforms with guidance from female industry mentors.',
    target_role: 'Full-Stack Web Development',
    is_external: true,
  },

  // =========================================================================
  // 3. RESEARCH & LABS (30 Items — Annual Global Open Shared Tasks & Benchmarks like SemEval)
  // Online / Global open challenges where Pakistani students build AI models, submit results & publish
  // =========================================================================
  {
    title: 'SemEval-2025 Task 1: Semantic Hallucination Detection in Large Language Models',
    organization: 'SemEval / ACL SIGLEX',
    type: 'Research',
    location: 'Online / Worldwide',
    deadline: 'Feb 15, 2026',
    status: 'Published',
    applicants_count: 310,
    match_requirement: 'Python · PyTorch · Transformers · NLP / LLM evaluation',
    featured: true,
    compensation: 'Official ACL Workshop Paper Publication & Proceedings',
    apply_url: 'https://semeval.github.io/SemEval2025',
    description: 'Annual competitive shared task held with the Association for Computational Linguistics (ACL). Teams build AI algorithms to detect when language models produce untrue or hallucinated facts.',
    target_role: 'AI / Machine Learning',
    is_external: true,
  },
  {
    title: 'SemEval-2025 Task 2: Multimodal Emotion and Sarcasm Reasoning in Videos',
    organization: 'SemEval / ACL SIGLEX',
    type: 'Research',
    location: 'Online / Worldwide',
    deadline: 'Feb 20, 2026',
    status: 'Published',
    applicants_count: 240,
    match_requirement: 'Computer Vision & Audio Processing · Multimodal Transformers · PyTorch',
    featured: true,
    compensation: 'Indexed in ACL Anthology + Global Leaderboard Ranking',
    apply_url: 'https://semeval.github.io/SemEval2025',
    description: 'Train computer vision and audio models to detect sarcasm and complex human emotions from video clips. Accepted system description papers are published in ACL Anthology.',
    target_role: 'Computer Vision',
    is_external: true,
  },
  {
    title: 'SemEval-2025 Task 3: Cross-Lingual Claim Verification & Factuality Scoring',
    organization: 'SemEval / ACL SIGLEX',
    type: 'Research',
    location: 'Online / Worldwide',
    deadline: 'Feb 25, 2026',
    status: 'Published',
    applicants_count: 195,
    match_requirement: 'Multilingual NLP · Cross-lingual embeddings · Information Retrieval',
    featured: false,
    compensation: 'ACL Workshop Paper Publication & Presentation',
    apply_url: 'https://semeval.github.io/SemEval2025',
    description: 'Detect whether online claims are supported or refuted by evidence across multiple languages. A benchmark challenge for students interested in NLP research.',
    target_role: 'AI / Machine Learning',
    is_external: true,
  },
  {
    title: 'SemEval-2025 Task 4: Multilingual Rhetorical Figure and Metaphor Detection',
    organization: 'SemEval / ACL SIGLEX',
    type: 'Research',
    location: 'Online / Worldwide',
    deadline: 'Mar 01, 2026',
    status: 'Published',
    applicants_count: 170,
    match_requirement: 'Computational Linguistics · Python · HuggingFace Transformers',
    featured: false,
    compensation: 'ACL Anthology Indexed System Paper',
    apply_url: 'https://semeval.github.io/SemEval2025',
    description: 'Evaluate AI models on identifying metaphorical sentences and figurative language across different languages. Top scoring student systems present at the SemEval workshop.',
    target_role: 'AI / Machine Learning',
    is_external: true,
  },
  {
    title: 'SemEval-2025 Task 5: Clinical Text Summarization and Patient Question Answering',
    organization: 'SemEval / ACL SIGLEX',
    type: 'Research',
    location: 'Online / Worldwide',
    deadline: 'Mar 05, 2026',
    status: 'Published',
    applicants_count: 215,
    match_requirement: 'BioNLP / Healthcare AI · Summarization models · Python',
    featured: false,
    compensation: 'ACL Workshop Paper + Open Source Benchmark Citation',
    apply_url: 'https://semeval.github.io/SemEval2025',
    description: 'Build safe, accurate natural language models that summarize doctor clinical notes and answer medical patient questions without introducing erroneous guidance.',
    target_role: 'Data Science & Analytics',
    is_external: true,
  },
  {
    title: 'CLEF CheckThat! Lab: Multilingual Fact-Checking & Fake News Detection',
    organization: 'Conference and Labs of the Evaluation Forum (CLEF)',
    type: 'Research',
    location: 'Online / Worldwide',
    deadline: 'Apr 30, 2026',
    status: 'Published',
    applicants_count: 260,
    match_requirement: 'Text classification · Feature engineering / Deep Learning · Python',
    featured: true,
    compensation: 'CEUR-WS Working Notes Publication & CLEF Conference Presentation',
    apply_url: 'https://checkthat.di.unipi.it',
    description: 'Annual European evaluation campaign. Participants build automated systems to estimate the check-worthiness of political tweets and detect verified misinformation.',
    target_role: 'AI / Machine Learning',
    is_external: true,
  },
  {
    title: 'CLEF eHealth Evaluation Lab: Information Extraction from Health Records',
    organization: 'CLEF Initiative',
    type: 'Research',
    location: 'Online / Worldwide',
    deadline: 'May 05, 2026',
    status: 'Published',
    applicants_count: 180,
    match_requirement: 'Named Entity Recognition (NER) · Information Extraction · Python',
    featured: false,
    compensation: 'CEUR-WS Peer-Reviewed Research Publication',
    apply_url: 'https://clefehealth.imag.fr',
    description: 'Annual research challenge on mining clinical entities, disease symptoms, and medication dosages from multilingual health reports.',
    target_role: 'Data Science & Analytics',
    is_external: true,
  },
  {
    title: 'CLEF Touché: Argument and Debate Retrieval Evaluation Challenge',
    organization: 'CLEF / Bauhaus-Universität Weimar',
    type: 'Research',
    location: 'Online / Worldwide',
    deadline: 'May 10, 2026',
    status: 'Published',
    applicants_count: 140,
    match_requirement: 'Information Retrieval · BM25 / Neural Search · PyTerrier or Python',
    featured: false,
    compensation: 'CEUR-WS Indexed Paper & Official Leaderboard',
    apply_url: 'https://touche.webis.de',
    description: 'Evaluate conversational search and argument retrieval. Your system must find convincing arguments from web forums for controversial public debate topics.',
    target_role: 'AI / Machine Learning',
    is_external: true,
  },
  {
    title: 'CLEF BioASQ: Large-Scale Biomedical Semantic Indexing & Question Answering',
    organization: 'BioASQ Consortium / European Commission',
    type: 'Research',
    location: 'Online / Worldwide',
    deadline: 'May 15, 2026',
    status: 'Published',
    applicants_count: 210,
    match_requirement: 'Semantic Search · Transformer QA · Medical text processing',
    featured: false,
    compensation: 'Springer LNCS Indexed Research Paper',
    apply_url: 'http://bioasq.org',
    description: 'Global benchmark challenge where researchers build systems to answer complex biomedical questions using the entire PubMed and MeSH medical literature database.',
    target_role: 'Data Science & Analytics',
    is_external: true,
  },
  {
    title: 'ImageCLEF: Multimodal Medical Concept Detection & Image Analysis',
    organization: 'ImageCLEF / CLEF Association',
    type: 'Research',
    location: 'Online / Worldwide',
    deadline: 'May 20, 2026',
    status: 'Published',
    applicants_count: 190,
    match_requirement: 'Computer Vision · CNNs / Vision Transformers · Medical X-Ray/CT Analysis',
    featured: true,
    compensation: 'CEUR-WS Conference Proceedings & Scientific Citations',
    apply_url: 'https://www.imageclef.org',
    description: 'Annual benchmark for multimodal computer vision. Classify medical imaging modalities, detect abnormalities in lung CT scans, and generate radiology text captions.',
    target_role: 'Computer Vision',
    is_external: true,
  },
  {
    title: 'TREC Deep Learning Track: Neural Ranking and Dense Retrieval Benchmark',
    organization: 'NIST (National Institute of Standards and Technology)',
    type: 'Research',
    location: 'Online / Worldwide',
    deadline: 'Jun 15, 2026',
    status: 'Published',
    applicants_count: 280,
    match_requirement: 'Dense Retrieval · Vector Search · MS MARCO dataset · Python',
    featured: true,
    compensation: 'NIST Special Publication & Industry-Standard Benchmark Status',
    apply_url: 'https://trec.nist.gov',
    description: 'The premier worldwide evaluation for search engines. Compete against Google, Microsoft, and university labs in ranking millions of web passages using neural models.',
    target_role: 'Data Science & Analytics',
    is_external: true,
  },
  {
    title: 'TREC Conversational Assistance Track (CAsT): Multi-Turn Dialogue Search',
    organization: 'NIST / University of Glasgow',
    type: 'Research',
    location: 'Online / Worldwide',
    deadline: 'Jun 25, 2026',
    status: 'Published',
    applicants_count: 160,
    match_requirement: 'Conversational Search · Query Rewriting · Context modeling · Python',
    featured: false,
    compensation: 'TREC Conference Proceedings & Academic Recognition',
    apply_url: 'https://www.treccast.ai',
    description: 'Design conversational search agents that can answer multi-turn information questions by resolving user pronouns, implicit context, and clarifying questions.',
    target_role: 'AI / Machine Learning',
    is_external: true,
  },
  {
    title: 'TREC CrisisLEX: Disaster Management & Social Media Incident Response',
    organization: 'NIST & QCRI (Qatar Computing Research Institute)',
    type: 'Research',
    location: 'Online / Worldwide',
    deadline: 'Jul 05, 2026',
    status: 'Published',
    applicants_count: 150,
    match_requirement: 'Social Media Mining · Real-time text classification · Python',
    featured: false,
    compensation: 'NIST Proceedings & Public Dataset Citations',
    apply_url: 'https://trec.nist.gov',
    description: 'Build real-time AI systems that filter urgent rescue requests, infrastructure damage, and medical emergencies from social media streams during natural disasters.',
    target_role: 'Data Science & Analytics',
    is_external: true,
  },
  {
    title: 'PAN at CLEF: Digital Text Forensics - Authorship Verification',
    organization: 'PAN Consortium / Bauhaus-Universität Weimar',
    type: 'Research',
    location: 'Online / Worldwide',
    deadline: 'May 30, 2026',
    status: 'Published',
    applicants_count: 200,
    match_requirement: 'Stylometry · NLP · Machine Learning · Text Forensics',
    featured: false,
    compensation: 'CEUR-WS Peer-Reviewed Research Publication',
    apply_url: 'https://pan.webis.de',
    description: 'Solve digital forensics challenges: determine whether two text documents were written by the same author using stylistic, grammatical, and lexical features.',
    target_role: 'Cybersecurity',
    is_external: true,
  },
  {
    title: 'PAN Multi-Author Analysis: Detecting AI-Generated & Plagiarized Text',
    organization: 'PAN Consortium',
    type: 'Research',
    location: 'Online / Worldwide',
    deadline: 'Jun 05, 2026',
    status: 'Published',
    applicants_count: 220,
    match_requirement: 'LLM detection · Perplexity analysis · Python · PyTorch',
    featured: false,
    compensation: 'CEUR-WS Working Notes Publication & Global Leaderboard',
    apply_url: 'https://pan.webis.de',
    description: 'Benchmark challenge on identifying boundary points where a human writer switched to another human or to an AI generation tool within a single essay or article.',
    target_role: 'AI / Machine Learning',
    is_external: true,
  },
  {
    title: 'WMT Annual Shared Task on Machine Translation (General MT)',
    organization: 'Conference on Machine Translation (WMT) / ACL',
    type: 'Research',
    location: 'Online / Worldwide',
    deadline: 'Jul 20, 2026',
    status: 'Published',
    applicants_count: 310,
    match_requirement: 'Seq2Seq models · Transformers · BLEU / COMET metrics · PyTorch',
    featured: true,
    compensation: 'ACL Anthology Peer-Reviewed Publication & Proceedings',
    apply_url: 'https://www.statmt.org/wmt24',
    description: 'The golden standard worldwide competition for machine translation. Build neural translation models between low-resource and high-resource language pairs.',
    target_role: 'AI / Machine Learning',
    is_external: true,
  },
  {
    title: 'WMT Shared Task on Quality Estimation & Automatic Post-Editing',
    organization: 'Conference on Machine Translation (WMT) / ACL',
    type: 'Research',
    location: 'Online / Worldwide',
    deadline: 'Jul 25, 2026',
    status: 'Published',
    applicants_count: 175,
    match_requirement: 'Quality Estimation · Cross-lingual models · Python · HuggingFace',
    featured: false,
    compensation: 'ACL Anthology Publication & Open Benchmark Citation',
    apply_url: 'https://www.statmt.org/wmt24',
    description: 'Predict the quality of translated text without relying on ground-truth human reference translations. Ideal for students specializing in applied NLP.',
    target_role: 'AI / Machine Learning',
    is_external: true,
  },
  {
    title: 'Kaggle Annual AI Research Challenge: Automated Math Reasoning',
    organization: 'Kaggle & AI Mathematical Olympiad (AIMO)',
    type: 'Research',
    location: 'Online / Worldwide',
    deadline: 'Aug 15, 2026',
    status: 'Published',
    applicants_count: 850,
    match_requirement: 'Large Language Models · Chain-of-Thought Reasoning · Python · PyTorch',
    featured: true,
    compensation: '$1,000,000 USD Prize Pool + Research Paper Citations',
    apply_url: 'https://www.kaggle.com/competitions',
    description: 'Train open-weights AI models to solve complex International Mathematical Olympiad (IMO) problems. Code submissions run directly on Kaggle cloud GPUs.',
    target_role: 'AI / Machine Learning',
    is_external: true,
  },
  {
    title: 'Kaggle Annual Research Challenge: Automated Essay Scoring 2.0',
    organization: 'Kaggle & The Learning Agency Lab',
    type: 'Research',
    location: 'Online / Worldwide',
    deadline: 'Jun 30, 2026',
    status: 'Published',
    applicants_count: 620,
    match_requirement: 'DeBERTa / Transformers · Regressors / Classifiers · Python · Pandas',
    featured: false,
    compensation: '$50,000 Cash Awards + Open-Source Benchmarks',
    apply_url: 'https://www.kaggle.com/competitions',
    description: 'Build predictive machine learning models that grade student writing samples accurately and impartially, reducing grading workloads for school teachers.',
    target_role: 'Data Science & Analytics',
    is_external: true,
  },
  {
    title: 'Kaggle Annual Research Challenge: LLM Hallucination Reduction in Science Q&A',
    organization: 'Kaggle & Open Source AI Community',
    type: 'Research',
    location: 'Online / Worldwide',
    deadline: 'Sep 01, 2026',
    status: 'Published',
    applicants_count: 540,
    match_requirement: 'Retrieval Augmented Generation (RAG) · Fine-tuning · Python',
    featured: false,
    compensation: '$50,000 Cash Prizes + Academic Papers',
    apply_url: 'https://www.kaggle.com/competitions',
    description: 'Evaluate open-source language models on complex scientific multiple-choice questions. Develop clever retrieval and prompt strategies to achieve state-of-the-art accuracy.',
    target_role: 'AI / Machine Learning',
    is_external: true,
  },
  {
    title: 'PhysioNet / Computing in Cardiology Challenge: ECG Anomaly Detection',
    organization: 'PhysioNet & MIT Laboratory for Computational Physiology',
    type: 'Research',
    location: 'Online / Worldwide',
    deadline: 'Aug 20, 2026',
    status: 'Published',
    applicants_count: 310,
    match_requirement: 'Signal processing · 1D CNNs / LSTMs · Python · NumPy / SciPy',
    featured: true,
    compensation: 'Computing in Cardiology (CinC) Peer-Reviewed Paper & Award',
    apply_url: 'https://physionet.org/about/challenge',
    description: 'The top global biomedical signal AI challenge. Build automated algorithms that analyze 12-lead electrocardiogram (ECG) recordings to identify heart rhythm abnormalities.',
    target_role: 'Data Science & Analytics',
    is_external: true,
  },
  {
    title: 'Grand Challenge in Biomedical Image Analysis: Brain Tumor Segmentation (BraTS)',
    organization: 'MICCAI Society & Grand Challenge Consortium',
    type: 'Research',
    location: 'Online / Worldwide',
    deadline: 'Jul 30, 2026',
    status: 'Published',
    applicants_count: 390,
    match_requirement: '3D U-Net · Computer Vision · PyTorch / MONAI · Medical MRI',
    featured: true,
    compensation: 'MICCAI LNCS Publication & Official Worldwide Leaderboard',
    apply_url: 'https://grand-challenge.org',
    description: 'The gold-standard annual biomedical vision challenge. Train 3D deep neural networks to segment multi-parametric MRI brain scans into healthy and tumor regions.',
    target_role: 'Computer Vision',
    is_external: true,
  },
  {
    title: 'Grand Challenge: Diabetic Retinopathy Screening Challenge',
    organization: 'Grand Challenge / IEEE Transactions on Medical Imaging',
    type: 'Research',
    location: 'Online / Worldwide',
    deadline: 'Aug 10, 2026',
    status: 'Published',
    applicants_count: 270,
    match_requirement: 'Retinal Fundus Image Analysis · Vision Transformers · PyTorch',
    featured: false,
    compensation: 'Open Global Benchmark Ranking & Scientific Papers',
    apply_url: 'https://grand-challenge.org',
    description: 'Detect microaneurysms and retinal hemorrhages in eye fundus photographs. Help develop automated AI tools that prevent blindness caused by diabetes.',
    target_role: 'Computer Vision',
    is_external: true,
  },
  {
    title: 'CoNLL Shared Task on Universal Dependency Parsing & Semantic Graphs',
    organization: 'SIGNLL / Association for Computational Linguistics (ACL)',
    type: 'Research',
    location: 'Online / Worldwide',
    deadline: 'Aug 18, 2026',
    status: 'Published',
    applicants_count: 180,
    match_requirement: 'Dependency parsing · Graph neural networks · Python',
    featured: false,
    compensation: 'ACL Anthology Indexed Publication',
    apply_url: 'https://www.conll.org',
    description: 'A classic computational linguistics shared task. Design neural parsers that map natural language sentences from 50+ languages into grammatical dependency tree graphs.',
    target_role: 'AI / Machine Learning',
    is_external: true,
  },
  {
    title: 'IberLEF: Evaluation of Human Language Technologies (Sentiment & Hate Speech)',
    organization: 'SEPLN (Spanish Society for NLP) / IberLEF',
    type: 'Research',
    location: 'Online / Worldwide',
    deadline: 'Jun 10, 2026',
    status: 'Published',
    applicants_count: 160,
    match_requirement: 'Text classification · Multilingual NLP · Python · Scikit-Learn',
    featured: false,
    compensation: 'CEUR-WS Open Access Proceedings & Certification',
    apply_url: 'https://sites.google.com/view/iberlef-2025',
    description: 'Annual shared tasks on detecting toxic comments, humorous tweets, and online harassment in multilingual social media text.',
    target_role: 'AI / Machine Learning',
    is_external: true,
  },
  {
    title: 'EVALITA: Periodic Evaluation Campaign of NLP & Speech Processing',
    organization: 'AILC (Italian Association of Computational Linguistics)',
    type: 'Research',
    location: 'Online / Worldwide',
    deadline: 'Jun 20, 2026',
    status: 'Published',
    applicants_count: 150,
    match_requirement: 'Speech recognition / Audio classification · NLP · Python',
    featured: false,
    compensation: 'CEUR-WS Indexed Workshop Paper',
    apply_url: 'https://www.evalita.it',
    description: 'Shared evaluation campaign testing speech transcription, named entity extraction, and acoustic sentiment models across diverse acoustic conditions.',
    target_role: 'Data Science & Analytics',
    is_external: true,
  },
  {
    title: 'SemDial / DialDoc Shared Task: Document-Grounded Conversational Agents',
    organization: 'ACL Special Interest Group on Dialogue',
    type: 'Research',
    location: 'Online / Worldwide',
    deadline: 'Jul 15, 2026',
    status: 'Published',
    applicants_count: 190,
    match_requirement: 'Dialogue Systems · RAG architectures · Python · PyTorch',
    featured: false,
    compensation: 'ACL Workshop Publication & Open Leaderboard',
    apply_url: 'https://doc2dial.github.io',
    description: 'Build conversational chatbots that answer user queries strictly according to long government or institutional policy documents without making assumptions.',
    target_role: 'AI / Machine Learning',
    is_external: true,
  },
  {
    title: 'BioNLP Open Shared Task: Gene-Disease Relation Extraction from PubMed',
    organization: 'BioNLP Community / ACL SIGBIO',
    type: 'Research',
    location: 'Online / Worldwide',
    deadline: 'Jul 05, 2026',
    status: 'Published',
    applicants_count: 175,
    match_requirement: 'Relation extraction · Knowledge Graphs · BioBERT · Python',
    featured: false,
    compensation: 'ACL SIGBIO Anthology Paper & Citations',
    apply_url: 'https://bionlp.nlm.nih.gov',
    description: 'Extract structured biomedical relations (such as which mutation causes a specific health condition) automatically from thousands of newly published medical journal papers.',
    target_role: 'Data Science & Analytics',
    is_external: true,
  },
  {
    title: 'PolEval: Annual Open Competition in Multilingual NLP Processing',
    organization: 'Institute of Computer Science, Polish Academy of Sciences',
    type: 'Research',
    location: 'Online / Worldwide',
    deadline: 'Aug 05, 2026',
    status: 'Published',
    applicants_count: 140,
    match_requirement: 'NLP text generation · Machine translation · Python',
    featured: false,
    compensation: 'Open Academic Leaderboard & Conference Proceedings',
    apply_url: 'http://poleval.pl',
    description: 'Open evaluation campaign focusing on lemmatization, punctuation restoration in automatic speech recognition, and cyberbullying detection.',
    target_role: 'AI / Machine Learning',
    is_external: true,
  },
  {
    title: 'SemEval-2026 Advance Call: Cross-Modal Reasoning & Commonsense Inference',
    organization: 'SemEval / ACL SIGLEX',
    type: 'Research',
    location: 'Online / Worldwide',
    deadline: 'Nov 30, 2026',
    status: 'Published',
    applicants_count: 260,
    match_requirement: 'Vision-Language models · Commonsense Reasoning · PyTorch',
    featured: true,
    compensation: 'Official ACL Workshop Paper Publication & Proceedings',
    apply_url: 'https://semeval.github.io',
    description: 'Next edition of SemEval shared tasks. Solve tricky multi-step visual puzzles and reasoning challenges that require understanding everyday physics and human intent.',
    target_role: 'AI / Machine Learning',
    is_external: true,
  },

  // =========================================================================
  // 4. SCHOLARSHIPS (30 Items — Fully Funded Master's / MS Degree in Asian, European & Global Countries)
  // 100% Fully Funded MS: Covers full tuition, monthly stipend, health insurance, airfare
  // =========================================================================
  {
    title: 'Erasmus Mundus Joint Masters Scholarship (EMJMD)',
    organization: 'European Commission',
    type: 'Scholarship',
    location: 'Multiple European Countries (France, Germany, Italy, Spain, etc.)',
    deadline: 'Jan 15, 2027',
    status: 'Published',
    applicants_count: 540,
    match_requirement: 'Completed 16 years of education (BS degree) · CGPA >= 3.0 · English proficiency (IELTS/TOEFL)',
    featured: true,
    compensation: 'Fully Funded: 100% Tuition + €1,400 / month Stipend + Airfare & Medical',
    apply_url: 'https://erasmus-plus.ec.europa.eu/opportunities/opportunities-for-individuals/students/erasmus-mundus-joint-masters',
    description: 'Prestigious European Union scholarship for a 2-year Master’s degree. You will study in at least two different European universities and earn a joint or double Master’s degree.',
    target_role: 'All',
    is_external: true,
  },
  {
    title: 'DAAD Helmut-Schmidt-Programme (Master’s in Public Policy & Tech Governance)',
    organization: 'German Academic Exchange Service (DAAD)',
    type: 'Scholarship',
    location: 'Germany (Top German Public Universities)',
    deadline: 'Jul 31, 2026',
    status: 'Published',
    applicants_count: 420,
    match_requirement: 'BS in Computing, Social Sciences, or Law · CGPA >= 3.0 · Relevant motivation',
    featured: true,
    compensation: 'Fully Funded: 100% Tuition + €934 / month + Health Insurance + Travel Grant',
    apply_url: 'https://www2.daad.de',
    description: 'Fully funded German government Master’s scholarship. Covers all living expenses, monthly stipend, health insurance, and 6-month free German language course.',
    target_role: 'All',
    is_external: true,
  },
  {
    title: 'DAAD Development-Related Postgraduate Courses (EPOS Master’s Programs)',
    organization: 'German Academic Exchange Service (DAAD)',
    type: 'Scholarship',
    location: 'Germany (Berlin, Munich, Stuttgart, RWTH Aachen)',
    deadline: 'Sep 30, 2026',
    status: 'Published',
    applicants_count: 390,
    match_requirement: '16-year Bachelor’s degree · 2 years of professional/internship experience · Strong motivation',
    featured: true,
    compensation: 'Fully Funded: Zero Tuition + €934 / month + Travel Allowance',
    apply_url: 'https://www.daad.de/en/study-and-research-in-germany/scholarships',
    description: 'Supports international students to pursue Master’s degrees in Engineering, Information Technology, Environmental Sciences, and Public Health at top public German institutions.',
    target_role: 'All',
    is_external: true,
  },
  {
    title: 'Chevening UK Government Master’s Scholarship',
    organization: 'UK Foreign, Commonwealth & Development Office (FCDO)',
    type: 'Scholarship',
    location: 'United Kingdom (Oxford, Cambridge, Imperial, UCL, Edinburgh)',
    deadline: 'Nov 04, 2026',
    status: 'Published',
    applicants_count: 610,
    match_requirement: 'Completed BS degree · 2 years of work experience · Strong leadership potential',
    featured: true,
    compensation: 'Fully Funded: 100% Tuition Fee + Monthly Living Allowance + Return Flight',
    apply_url: 'https://www.chevening.org/scholarships',
    description: 'The UK government’s premier global scholarship program. Covers complete tuition for a one-year Master’s degree at any top university in the UK, plus all living costs.',
    target_role: 'All',
    is_external: true,
  },
  {
    title: 'Eiffel Excellence Scholarship Program (Master’s Degree)',
    organization: 'French Ministry for Europe and Foreign Affairs',
    type: 'Scholarship',
    location: 'France (Sorbonne, École Polytechnique, PSL)',
    deadline: 'Jan 10, 2027',
    status: 'Published',
    applicants_count: 310,
    match_requirement: 'Top academic record in Bachelor’s · Age up to 25 · Nominated by a French university',
    featured: true,
    compensation: 'Fully Funded: €1,181 / month Living Allowance + Flights + Social Security',
    apply_url: 'https://www.campusfrance.org/en/eiffel-scholarship-program-of-excellence',
    description: 'Designed by the French government to attract the best international Master’s students in Computer Science, Artificial Intelligence, Engineering, and Economics to France.',
    target_role: 'All',
    is_external: true,
  },
  {
    title: 'MEXT Japanese Government Master’s Scholarship (Embassy Recommendation)',
    organization: 'Ministry of Education, Culture, Sports, Science & Tech (Japan)',
    type: 'Scholarship',
    location: 'Japan (University of Tokyo, Kyoto University, Tokyo Tech)',
    deadline: 'May 20, 2026',
    status: 'Published',
    applicants_count: 480,
    match_requirement: 'Completed 16 years of education · Pakistani citizen under 35 · Written test & interview',
    featured: true,
    compensation: 'Fully Funded: 100% Tuition + 144,000 JPY / month Stipend + Return Flights',
    apply_url: 'https://www.pk.emb-japan.go.jp/itpr_en/MEXTScholarship.html',
    description: 'One of the most generous scholarships in Asia. The Japanese government pays your full university fees, provides return air tickets, and gives a monthly allowance for your MS degree.',
    target_role: 'All',
    is_external: true,
  },
  {
    title: 'Global Korea Scholarship (GKS - Graduate Master’s Program)',
    organization: 'National Institute for International Education (NIIED), South Korea',
    type: 'Scholarship',
    location: 'South Korea (Seoul National University, KAIST, POSTECH)',
    deadline: 'Mar 15, 2027',
    status: 'Published',
    applicants_count: 450,
    match_requirement: 'CGPA >= 2.64/4.0 or top 20% · Bachelor’s degree holder under 40 · Good health',
    featured: true,
    compensation: 'Fully Funded: 100% Tuition + 1,000,000 KRW / month + Airfare & Medical',
    apply_url: 'https://www.studyinkorea.go.kr',
    description: 'South Korea’s flagship government scholarship for an MS degree. Includes 1 full year of intensive Korean language training followed by a 2-year Master’s degree at a Korean university.',
    target_role: 'All',
    is_external: true,
  },
  {
    title: 'Turkiye Burslari Master’s Scholarship Program',
    organization: 'Government of the Republic of Turkey',
    type: 'Scholarship',
    location: 'Turkey (METU, Bogazici, ITU, Bilkent University)',
    deadline: 'Feb 20, 2027',
    status: 'Published',
    applicants_count: 590,
    match_requirement: 'Bachelor’s CGPA >= 75% · Under 30 years old · Online application & interview',
    featured: true,
    compensation: 'Fully Funded: 100% Tuition + Monthly Stipend + Free Dormitory + Flights',
    apply_url: 'https://www.turkiyeburslari.gov.tr',
    description: 'Comprehensive scholarship offered by the Turkish Government. Covers university placement, free dorm accommodation, Turkish language course, health insurance, and monthly pocket money.',
    target_role: 'All',
    is_external: true,
  },
  {
    title: 'Chinese Government Scholarship (CSC Silk Road & High-Level Master’s)',
    organization: 'China Scholarship Council (CSC)',
    type: 'Scholarship',
    location: 'China (Tsinghua, Peking University, Zhejiang University)',
    deadline: 'Apr 05, 2026',
    status: 'Published',
    applicants_count: 520,
    match_requirement: 'Bachelor’s degree holder under 35 · Good academic standing · Physical exam certificate',
    featured: true,
    compensation: 'Fully Funded: 100% Tuition + 3,000 RMB / month Stipend + Free Accommodation',
    apply_url: 'https://www.campuschina.org',
    description: 'Complete Chinese government funding for international Master’s degree programs. Full waiver of tuition fees, free university campus housing, medical insurance, and monthly living allowance.',
    target_role: 'All',
    is_external: true,
  },
  {
    title: 'Swedish Institute Scholarship for Global Professionals (Master’s Studies)',
    organization: 'Swedish Institute (SI) / Government of Sweden',
    type: 'Scholarship',
    location: 'Sweden (KTH Royal Institute of Technology, Lund, Uppsala)',
    deadline: 'Feb 28, 2027',
    status: 'Published',
    applicants_count: 380,
    match_requirement: 'BS degree · Minimum 3,000 hours of demonstrated work experience · Leadership',
    featured: true,
    compensation: 'Fully Funded: Full Tuition + SEK 12,000 / month Living Expense + Travel Grant',
    apply_url: 'https://si.se/en/apply/scholarships/swedish-institute-scholarships-for-global-professionals',
    description: 'Fully funded Swedish government scholarship covering full tuition fees and providing a generous monthly stipend of 12,000 SEK to study a Master’s degree in Sweden.',
    target_role: 'All',
    is_external: true,
  },
  {
    title: 'Swiss Government Excellence Scholarships (Master’s / Research Fellowships)',
    organization: 'Federal Commission for Scholarships for Foreign Students (FCS)',
    type: 'Scholarship',
    location: 'Switzerland (ETH Zurich, EPFL, University of Zurich)',
    deadline: 'Nov 12, 2026',
    status: 'Published',
    applicants_count: 290,
    match_requirement: 'Bachelor’s degree with outstanding academic distinction · Research proposal',
    featured: true,
    compensation: 'Fully Funded: CHF 1,920 / month Living Stipend + Health Insurance + Housing Allowance',
    apply_url: 'https://www.sbfi.admin.ch/scholarships_eng',
    description: 'Prestigious fellowship awarded by the Swiss Confederation to pursue advanced Master’s research and postgraduate studies at world-renowned institutes like ETH Zurich and EPFL.',
    target_role: 'All',
    is_external: true,
  },
  {
    title: 'Stipendium Hungaricum Master’s Scholarship',
    organization: 'Tempus Public Foundation / Government of Hungary',
    type: 'Scholarship',
    location: 'Hungary (Eötvös Loránd University - ELTE, BME Budapest)',
    deadline: 'Jan 15, 2027',
    status: 'Published',
    applicants_count: 630,
    match_requirement: 'Nominated through HEC Pakistan HAT Test · Completed 16 years of education',
    featured: true,
    compensation: 'Fully Funded: 100% Tuition + Monthly Allowance + Free Dormitory + Medical Insurance',
    apply_url: 'https://stipendiumhungaricum.hu',
    description: 'Bilateral scholarship program between Hungary and Pakistan. Free tuition, free university student dormitory, health insurance, and monthly allowance for a 2-year Master’s.',
    target_role: 'All',
    is_external: true,
  },
  {
    title: 'SINGA - Singapore International Graduate Master’s/PhD Award',
    organization: 'Agency for Science, Technology & Research (A*STAR), NTU, NUS',
    type: 'Scholarship',
    location: 'Singapore (National University of Singapore - NUS, NTU)',
    deadline: 'Jun 01, 2026',
    status: 'Published',
    applicants_count: 410,
    match_requirement: 'Graduates with passion for research in Computing / AI / Science · Excellent grades',
    featured: true,
    compensation: 'Fully Funded: Full Tuition + S$ 2,700 - 3,200 / month + Airfare Grant',
    apply_url: 'https://www.a-star.edu.sg/Scholarships/for-graduate-studies/singapore-international-graduate-award-singa',
    description: 'Study at NUS or NTU (consistently ranked top 15 in the world). Singapore government provides 100% tuition, return flight ticket, settling-in allowance, and a generous monthly stipend.',
    target_role: 'All',
    is_external: true,
  },
  {
    title: 'Commonwealth Master’s Scholarships (UK for Developing Countries)',
    organization: 'Commonwealth Scholarship Commission (CSC)',
    type: 'Scholarship',
    location: 'United Kingdom (Top UK Public Universities)',
    deadline: 'Dec 12, 2026',
    status: 'Published',
    applicants_count: 510,
    match_requirement: 'Citizen of Commonwealth country (Pakistan) · BS degree with 1st division · Cannot afford UK study alone',
    featured: true,
    compensation: 'Fully Funded: Full Tuition Fees + £1,347 / month Stipend + Flights & Warm Clothing Allowance',
    apply_url: 'https://cscuk.fcdo.gov.uk/scholarships/commonwealth-masters-scholarships',
    description: 'Enables talented students from Pakistan to complete a 1-year taught Master’s degree at leading UK universities with all airfares, course fees, and monthly living allowances covered.',
    target_role: 'All',
    is_external: true,
  },
  {
    title: 'VLIR-UOS Master’s Scholarship Program (Belgium)',
    organization: 'Government of Flanders / VLIR-UOS',
    type: 'Scholarship',
    location: 'Belgium (KU Leuven, Ghent University, University of Antwerp)',
    deadline: 'Feb 01, 2027',
    status: 'Published',
    applicants_count: 270,
    match_requirement: 'Bachelor’s degree from developing country · Age under 35 · Relevant work experience',
    featured: false,
    compensation: 'Fully Funded: Full Tuition + Monthly Allowance €1,400 + Housing + Flight',
    apply_url: 'https://www.vliruos.be/en/scholarships',
    description: 'Full financial support for selected English-taught Master’s programs in Belgium. Covers your full tuition, international flight, housing costs, and monthly living money.',
    target_role: 'All',
    is_external: true,
  },
  {
    title: 'Taiwan ICDF International Higher Education Master’s Scholarship',
    organization: 'International Cooperation & Development Fund (TaiwanICDF)',
    type: 'Scholarship',
    location: 'Taiwan (National Taiwan University, National Tsing Hua University)',
    deadline: 'Mar 15, 2027',
    status: 'Published',
    applicants_count: 260,
    match_requirement: 'Bachelor’s degree holder · Good English language proficiency · Clean background',
    featured: false,
    compensation: 'Fully Funded: Full Tuition + NT$ 18,000 / month Stipend + Dormitory & Flights',
    apply_url: 'https://www.icdf.org.tw',
    description: 'Full scholarship covering return economy airfare, student housing, full tuition fees, insurance, textbook costs, and a monthly living allowance of NT$ 18,000 for Master’s students.',
    target_role: 'All',
    is_external: true,
  },
  {
    title: 'Brunei Darussalam Government Scholarship (BDGS Master’s Program)',
    organization: 'Ministry of Foreign Affairs, Brunei Darussalam',
    type: 'Scholarship',
    location: 'Brunei (Universiti Brunei Darussalam - UBD, UTB)',
    deadline: 'Feb 15, 2027',
    status: 'Published',
    applicants_count: 210,
    match_requirement: 'Citizens of Commonwealth / OIC countries (Pakistan) · Age between 18-35',
    featured: false,
    compensation: 'Fully Funded: 100% Tuition + BND 500 / month Stipend + Accommodation + Airfare',
    apply_url: 'http://www.mfa.gov.bn/pages/bdgs',
    description: 'Annual scholarship funded by the Government of Brunei Darussalam for Master’s degrees. Covers round-trip airfare, complete tuition fee exemption, on-campus accommodation, and baggage allowance.',
    target_role: 'All',
    is_external: true,
  },
  {
    title: 'Royal Thai Government Asian Institute of Technology (AIT) Master’s Fellowships',
    organization: 'Royal Thai Government & AIT',
    type: 'Scholarship',
    location: 'Thailand (Asian Institute of Technology, Pathum Thani)',
    deadline: 'Jun 10, 2026',
    status: 'Published',
    applicants_count: 240,
    match_requirement: 'BS in Computing, Civil, Environmental, or Management · CGPA >= 3.0 · English proficiency',
    featured: false,
    compensation: 'Fully Funded: Full Tuition + Monthly Accommodation & Living Allowances',
    apply_url: 'https://ait.ac.th/admissions/scholarships',
    description: 'Endowed by His Majesty the King of Thailand. Covers full tuition, registration fees, and living costs for qualified candidates across Asian countries to pursue Master’s studies.',
    target_role: 'All',
    is_external: true,
  },
  {
    title: 'Chulalongkorn University Graduate Scholarship for ASEAN & Non-ASEAN Countries',
    organization: 'Chulalongkorn University',
    type: 'Scholarship',
    location: 'Bangkok, Thailand (Chulalongkorn University)',
    deadline: 'May 15, 2026',
    status: 'Published',
    applicants_count: 220,
    match_requirement: 'Completed Bachelor’s degree · CGPA >= 3.25 · Good English test score',
    featured: false,
    compensation: 'Fully Funded: Full Tuition + 16,000 THB / month Stipend + Accommodation',
    apply_url: 'https://www.academic.chula.ac.th',
    description: 'Chulalongkorn is Thailand’s oldest and highest-ranking university. Provides complete tuition waivers, economy-class airfare, and a monthly stipend of 16,000 Baht for 2-year MS degrees.',
    target_role: 'All',
    is_external: true,
  },
  {
    title: 'Khalifa University Master’s Research Scholarship (GRS)',
    organization: 'Khalifa University of Science and Technology',
    type: 'Scholarship',
    location: 'Abu Dhabi, United Arab Emirates',
    deadline: 'Apr 30, 2026',
    status: 'Published',
    applicants_count: 340,
    match_requirement: 'BS in Computer Science, AI, or Engineering · CGPA >= 3.25 · GRE/IELTS',
    featured: true,
    compensation: 'Fully Funded: 100% Tuition + AED 4,000 / month Stipend + Medical Insurance',
    apply_url: 'https://www.ku.ac.ae/scholarships',
    description: 'Ranked top university in the UAE. Offers full tuition support, comprehensive medical insurance, textbooks, visa sponsorship, and a monthly stipend of AED 4,000 during your MS degree.',
    target_role: 'All',
    is_external: true,
  },
  {
    title: 'King Fahd University (KFUPM) Full MS Fellowship',
    organization: 'King Fahd University of Petroleum and Minerals',
    type: 'Scholarship',
    location: 'Dhahran, Saudi Arabia',
    deadline: 'Jul 20, 2026',
    status: 'Published',
    applicants_count: 430,
    match_requirement: 'Bachelor’s degree in CS, EE, or related STEM · Strong CGPA · GRE recommended',
    featured: true,
    compensation: 'Fully Funded: Full Tuition + Monthly Stipend + Furnished Housing + Flights',
    apply_url: 'https://postgrad.kfupm.edu.sa',
    description: 'KFUPM is the top-ranked university in the Middle East for engineering and computing. All admitted MS students receive full tuition waiver, free housing, medical care, and monthly stipends.',
    target_role: 'All',
    is_external: true,
  },
  {
    title: 'Holland Scholarship & Orange Knowledge Programme (Master’s in Netherlands)',
    organization: 'Dutch Ministry of Education & Nuffic',
    type: 'Scholarship',
    location: 'Netherlands (TU Delft, University of Amsterdam, Eindhoven TU)',
    deadline: 'Feb 01, 2027',
    status: 'Published',
    applicants_count: 310,
    match_requirement: 'Admitted to an eligible English-taught Master’s in Netherlands · Strong academic record',
    featured: false,
    compensation: 'Full Tuition Grant + Monthly Living Subsidy',
    apply_url: 'https://www.studyinnl.org/finances/nl-scholarship',
    description: 'Financed by the Dutch Ministry of Education, Culture and Science. Supports international students studying at research universities and universities of applied sciences in the Netherlands.',
    target_role: 'All',
    is_external: true,
  },
  {
    title: 'Invest Your Talent in Italy (IYT Master’s Scholarship)',
    organization: 'Italian Ministry of Foreign Affairs & International Cooperation',
    type: 'Scholarship',
    location: 'Italy (Politecnico di Milano, Politecnico di Torino, Sapienza)',
    deadline: 'Mar 01, 2027',
    status: 'Published',
    applicants_count: 280,
    match_requirement: 'Bachelor’s degree in Engineering, Computer Science, or Management · English proficiency',
    featured: false,
    compensation: 'Fully Funded: 100% Tuition Fee Exemption + €900 / month Living Allowance',
    apply_url: 'https://postgradinitaly.esteri.it',
    description: 'Study a Master’s degree in English in Italy. Combines academic studies with on-the-job training and an internship at leading Italian engineering and tech firms.',
    target_role: 'All',
    is_external: true,
  },
  {
    title: 'Government of Ireland International Education Master’s Scholarship (GOI-IES)',
    organization: 'Higher Education Authority (HEA) Ireland',
    type: 'Scholarship',
    location: 'Ireland (Trinity College Dublin, University College Dublin)',
    deadline: 'Mar 24, 2027',
    status: 'Published',
    applicants_count: 270,
    match_requirement: 'Outstanding academic record · Offer letter for 1-year Master’s degree in Ireland',
    featured: false,
    compensation: 'Fully Funded: Full Tuition Waiver + €10,000 Annual Living Stipend',
    apply_url: 'https://hea.ie/funding-governance-performance/funding/student-finance/government-of-ireland-international-education-scholarships',
    description: 'Awarded by the Government of Ireland to top international students. Covers full tuition and registration fees plus an individual living stipend of €10,000 for one year of Master’s study.',
    target_role: 'All',
    is_external: true,
  },
  {
    title: 'Gates Cambridge Master’s Scholarship',
    organization: 'Bill and Melinda Gates Foundation',
    type: 'Scholarship',
    location: 'United Kingdom (University of Cambridge)',
    deadline: 'Dec 05, 2026',
    status: 'Published',
    applicants_count: 380,
    match_requirement: 'Outstanding intellectual ability · Reasons for choice of course · Commitment to helping others',
    featured: true,
    compensation: 'Fully Funded: Full University Composition Fee + £20,000 / year Maintenance + Airfare',
    apply_url: 'https://www.gatescambridge.org',
    description: 'One of the most prestigious international scholarships in the world. Covers the full cost of studying a Master’s degree at the University of Cambridge plus discretionary discretionary funds.',
    target_role: 'All',
    is_external: true,
  },
  {
    title: 'Oxford Clarendon Fund Master’s Scholarship',
    organization: 'University of Oxford Clarendon Fund',
    type: 'Scholarship',
    location: 'United Kingdom (University of Oxford)',
    deadline: 'Jan 08, 2027',
    status: 'Published',
    applicants_count: 360,
    match_requirement: 'Automatic consideration when applying for an Oxford Master’s course before January deadline',
    featured: true,
    compensation: 'Fully Funded: 100% Course Fees + Generous Annual Living Cost Grant',
    apply_url: 'https://www.ox.ac.uk/clarendon',
    description: 'Clarendon offers over 160 new fully-funded scholarships every year for graduate students at Oxford. Covers tuition and college fees in full alongside generous living expense grants.',
    target_role: 'All',
    is_external: true,
  },
  {
    title: 'Australia Awards Master’s Scholarship (DFAT)',
    organization: 'Australian Government (Department of Foreign Affairs & Trade)',
    type: 'Scholarship',
    location: 'Australia (University of Melbourne, Australian National University, Sydney)',
    deadline: 'Apr 30, 2026',
    status: 'Published',
    applicants_count: 490,
    match_requirement: 'Pakistani citizen · At least 2 years of work experience · Bachelor’s degree',
    featured: true,
    compensation: 'Fully Funded: Full Tuition + Return Airfare + AUD 3,000+ / month Living Allowance',
    apply_url: 'https://www.dfat.gov.au/people-to-people/australia-awards',
    description: 'Long-term scholarships administered by Australia’s DFAT. Covers 100% university tuition fees, return air travel, establishment allowance, and contribution to living expenses (CLE).',
    target_role: 'All',
    is_external: true,
  },
  {
    title: 'New Zealand Manaaki Master’s Scholarships',
    organization: 'Ministry of Foreign Affairs and Trade (MFAT) New Zealand',
    type: 'Scholarship',
    location: 'New Zealand (University of Auckland, Victoria University of Wellington)',
    deadline: 'Feb 28, 2027',
    status: 'Published',
    applicants_count: 240,
    match_requirement: 'Citizen of eligible developing country · Minimum 1-2 years relevant experience',
    featured: false,
    compensation: 'Fully Funded: Full Tuition + NZ$ 531 / week Living Allowance + Airfare & Medical',
    apply_url: 'https://www.mfat.govt.nz/en/aid-and-development/scholarships',
    description: 'Government of New Zealand scholarships for postgraduate study. Full tuition fee coverage, living allowance of NZ$ 531 per week, medical insurance, and international return flights.',
    target_role: 'All',
    is_external: true,
  },
  {
    title: 'Hong Kong Postgraduate Master’s Scholarship (HKU & CUHK)',
    organization: 'University Grants Committee of Hong Kong',
    type: 'Scholarship',
    location: 'Hong Kong (University of Hong Kong - HKU, CUHK, HKUST)',
    deadline: 'Dec 01, 2026',
    status: 'Published',
    applicants_count: 290,
    match_requirement: 'Outstanding Bachelor’s degree in STEM · Research intent · English proficiency',
    featured: false,
    compensation: 'Fully Funded: Full Tuition Waiver + HK$ 18,000 / month Living Allowance',
    apply_url: 'https://gradsch.hku.hk',
    description: 'Generous postgraduate studentship provided by top Hong Kong universities. Covers all academic tuition fees and provides a tax-free monthly allowance of HK$ 18,000 for Master of Philosophy/MS degrees.',
    target_role: 'All',
    is_external: true,
  },
  {
    title: 'Fulbright Foreign Student Program (Master’s in the United States)',
    organization: 'US Department of State & USEFP (Pakistan Chapter)',
    type: 'Scholarship',
    location: 'United States (Top Universities across the USA)',
    deadline: 'May 10, 2026',
    status: 'Published',
    applicants_count: 720,
    match_requirement: 'Pakistani citizen · 16 years of formal education (BS degree) · GRE General Test',
    featured: true,
    compensation: 'Fully Funded: 100% Tuition + Living Stipend + Health Insurance + Airfare',
    apply_url: 'https://www.usefp.org/scholarships/fulbright-degree.cfm',
    description: 'Pakistan has the world’s largest Fulbright program. Covers complete tuition, textbooks, monthly living stipend, health insurance, and round-trip air travel for a Master’s in the USA.',
    target_role: 'All',
    is_external: true,
  },
];

export async function seedComprehensiveOpportunities() {
  console.log(`Starting to seed ${COMPREHENSIVE_OPPORTUNITIES.length} authentic opportunities...`);

  // Ensure necessary columns exist in opportunities table
  await query(`
    ALTER TABLE opportunities 
    ADD COLUMN IF NOT EXISTS apply_url TEXT,
    ADD COLUMN IF NOT EXISTS description TEXT,
    ADD COLUMN IF NOT EXISTS target_role TEXT DEFAULT 'All',
    ADD COLUMN IF NOT EXISTS is_external BOOLEAN DEFAULT TRUE;
  `);

  // Wipe previous opportunities so only the 120 authentic items exist
  await query('DELETE FROM applications;');
  await query('DELETE FROM opportunities;');

  let count = 0;
  for (const opp of COMPREHENSIVE_OPPORTUNITIES) {
    await query(
      `INSERT INTO opportunities (
        title,
        organization,
        type,
        location,
        deadline,
        status,
        applicants_count,
        match_requirement,
        featured,
        compensation,
        apply_url,
        description,
        target_role,
        is_external
      ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)`,
      [
        opp.title,
        opp.organization,
        opp.type,
        opp.location,
        opp.deadline,
        opp.status,
        opp.applicants_count,
        opp.match_requirement,
        opp.featured,
        opp.compensation,
        opp.apply_url,
        opp.description,
        opp.target_role,
        opp.is_external,
      ]
    );
    count++;
  }

  console.log(`Successfully seeded ${count} authentic opportunities into PostgreSQL database!`);
}

// Run directly if called via CLI
if (process.argv[1]?.includes('seedOpportunities')) {
  seedComprehensiveOpportunities()
    .then(() => process.exit(0))
    .catch((err) => {
      console.error('Seeding error:', err);
      process.exit(1);
    });
}
